### ISSUE TITLE
also add go-ethereum into test network

### ISSUE THREAD

**Issue by sveneh** [ethereum/system-testing#30]

**Comment by heikoheiko** [comment]
we also need to set params on the cl when starting, at least:
- coinbase
- pubkey/nodeid
- mining_percentage
- num_peers
- bootstrapping host
- rpc listening port
- rlpx listening port
- datadir

**Comment by tgerring** [comment]
Here's the initial information to support the requested params:

coinbase `-import="/path/to/secretfile"`
pubkey/nodeid `-identifier="CustomClientName"`
mining_percentage `-mine=true` (Mining as a % of CPU time not currently available)
num_peers `-maxpeers=30`
bootstrapping host `-seednode="ip:port"` (pending PR 287)
rpc listening port `-rpcport=8080`
rlpx listening port `-port=30303`
datadir `-datadir="~/.ethereum"`

Some items may need to changes to achieve full functionality. In particular, some clarification around input format and intended functionality for coinbase & pubkey/nodeid would be helpful, as these codebases are under active development.

**Comment by fjl** [comment]
@heikoheiko it is not possible to set the node ID directly as a parameter. we can only provide a flag for the private key. the actual node id will then be derived from that key.

**Comment by heikoheiko** [comment]
@fjl yes, makes sense. 
ideally we'd be able to set the privkey (not the path) as a cl parameter. otherwise we have to create additional files in docker.

**Comment by fjl** [comment]
I will make sure that this is possible.

**Comment by fjl** [comment]
In the [poc8-net-integration](https://github.com/ethereum/go-ethereum/pulls/292) branch, both mist and ethereum accept the required flags for discovery testing.

As an example, you can generate a key like this:
    
    NODEKEY=`openssl rand -hex 32`

and then run ethereum as 

    ethereum -nodekeyhex $NODEKEY -bootnodes " enode://244b2b8c8ba050c0b1564bf1ffd414459680f357f00ffca4f4cb78056c2fdc56c67e79ce93984cfc436f39445ae3cd247f933a0b598818c1aaa020993888a021@127.0.0.1:30303"

**Comment by sveneh** [comment]
need to address poc8 integration changes
