### ISSUE TITLE
client numbered naming

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/system-testing#40]
the current scheme 'client-01', 'client-02', ... limits us to 100 peers. 
should be increased to 100k addressable range. 

proposal:
get rid of the leading zero, to get rid of the limit. and start counting with zero.
e.g. client-0, client-1, ... client-213412451

**Comment by heikoheiko** [comment]
we agreed on 5 digits, `client-00001'

**Comment by sveneh** [comment]
naming will be as described here
https://github.com/ethereum/system-testing/wiki/Multi-client-support-on-one-instance
