### ISSUE TITLE
go client: implement all defined log events

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/system-testing#54]
https://github.com/ethereum/system-testing/wiki/Log-Events

**Comment by heikoheiko** [comment]
@tgerring when can we expect to get your changes merged?

**Comment by tgerring** [comment]
`eth.tx.received` and `eth.miner.new_block` added in ethereum/go-ethereum#409

@zelig to add `eth.chain.received.new_block` and `eth.chain.new_head`

**Comment by sveneh** [comment]
Waiting for merge from @zelig

**Comment by tgerring** [comment]
@sveneh logs should be merged into develop
